-- Handy SQL snippets
DELETE FROM BORDERPOINT WHERE LOCATIONID IN (SELECT LOCATIONID FROM LOCATION WHERE COUNTYFP IS NOT NULL);
DELETE FROM LOCATION WHERE COUNTYFP IS NOT NULL;

SELECT COUNT(*) FROM BORDERPOINT WHERE LOCATIONID IN (SELECT LOCATIONID FROM LOCATION WHERE COUNTYFP IS NOT NULL);
select count(*) from location where countyfp is not null;